@hostname = http://localhost:8000
@api_user_path = '/api/user/'
get {{hostname}}

###
get {{hostname}}/api/users

### 
get {{hostname}}/api/users/condition

###
get {{hostname}}/api/users/659ab167feea355e370f0259

###
get {{hostname}}/api/users?email=prince.shukla@gmail.com

###
POST {{hostname}}/api/users/659c5b074612700e9df84582 HTTP/1.1
Content-Type: application/json

{
    "phone": 9981966624
}

###
POST {{hostname}}/api/users/add
Content-Type: application/json

{
    "name": "Shubhangi Seth",
    "email": "shubhangi.seth@gmail.com",
    "phone": 81879966624,
    "place": "Dubai"
}

###
POST {{hostname}}/api/users/register
Content-Type: application/json

{
    "email": "aditya.raj@gmail.com",
    "password": "Adi@123"
}

###
POST {{hostname}}/api/users/login
Content-Type: application/json

{
    "email": "shubham.seth@gmail.com",
    "password": "Shu@123"
}

###
POST {{hostname}}{{api_user_path}}forgot-password
Content-Type: application/json

{
    "email": "shubham.seth@gmail.com"
}

###
POST {{hostname}}{{api_user_path}}reset-password
Content-Type: application/json

{
    "resetToken": "",
    "newPassword": ""
}